from pathlib import Path

KFOLDS=20
DATAROOT = Path("/p/scratch/atmlaml/steinbach1/sota_on_uncertainties/data/")
IMGNSTEMS=[
"n01440764",
"n02102040",
"n02979186",
"n03000684",
"n03028079",
"n03394916",
"n03417042",
"n03425413",
"n03445777",
"n03888257"
    ]

    
rule imagenette_folds:
    input:
        expand(DATAROOT / "imagenette2-320-splits"/"fold-{fid:02.0f}/{category}",
               fid=range(KFOLDS),
               category="train val".split(' ')
               )

rule imagenette_all:
    input: expand(DATAROOT / "imagenette2-320-all/{dir}",dir=IMGNSTEMS)

rule imagenette_unpack:
    input: "imagenette2-320.tgz"
    output: rootdir=directory(DATAROOT / "data"),
            tocheck1=DATAROOT / "imagenette2-320/val/n02979186/n02979186_7492.JPEG",
            tocheck2=DATAROOT / "imagenette2-320/noisy_imagenette.csv"
    shell: "cd {output.rootdir} && tar xf ../{input}"


rule imagenette_combine:
    input: DATAROOT / "{dataset}" /"val"/"{classdir}",
           DATAROOT / "{dataset}" /"train"/"{classdir}"
    output: directory(DATAROOT / "{dataset}-all/{classdir}")
    shell: "mkdir -p {output[0]} && cp -vur {input[0]}/*JPEG {input[1]}/*JPEG {output[0]}"

rule create_tables:
    input: DATAROOT / "{dataset}-all"
    output: expand(DATAROOT / "{{dataset}}-splits"/"fold-{fid:02.0f}.table", fid=range(KFOLDS))
    script:
        "scripts/kfold.py"

rule imagenette_tables:
    input: expand(DATAROOT / "imagenette2-320-splits"/"fold-{fid:02.0f}.table", fid=range(KFOLDS))

rule fill_fold:
    input: DATAROOT / "{dataset}-splits"/"fold-{foldid}.table"
    output: directory(DATAROOT / "{dataset}-splits"/"fold-{foldid}"),
            directory(DATAROOT / "{dataset}-splits"/"fold-{foldid}/train"),
            directory(DATAROOT / "{dataset}-splits"/"fold-{foldid}/val")
    script:
        "scripts/linkin.py"

rule imagenette2_resnet50_default:
    input: DATAROOT/"imagenette2-320-splits"/"{foldstem}"
    output: directory("outputs/resnet50/seed42/{foldstem}/"), "outputs/resnet50/seed42/{foldstem}/after80/last.pth.tar"
    log: "outputs/resnet50/seed42/{foldstem}.log"
    shell: "python timm-0.5.4-train.py {input} --model resnet50 --num-classes=10 --output {output[0]} --checkpoint-hist 2 --epochs 80 --experiment after80 > {log} 2>&1"

rule imagenette2_resnext50_default:
    input: DATAROOT/"imagenette2-320-splits"/"{foldstem}"
    output: directory("outputs/resnext50/seed42/{foldstem}/"), "outputs/resnext50/seed42/{foldstem}/after80/last.pth.tar"
    log: "outputs/resnext50/seed42/{foldstem}.log"
    shell: "python timm-0.5.4-train.py {input} --num-classes=10 --output {output[0]} --experiment after80 --model resnext50_32x4d --checkpoint-hist 2 --lr 0.6 --warmup-epochs 5 --epochs 80 --weight-decay 1e-4 --sched cosine --reprob 0.4 --recount 3 --remode pixel --aa rand-m7-mstd0.5-inc1 -b 192 -j 6 --amp --dist-bn reduce > {log} 2>&1"

rule imagenette2_vit_small_default:
    input: DATAROOT/"imagenette2-320-splits"/"{foldstem}"
    output: directory("outputs/vit_small/seed42/{foldstem}/"), "outputs/vit_small/seed42/{foldstem}/after80/last.pth.tar"
    log: "outputs/vit_small/seed42/{foldstem}.log"
    shell: "python timm-0.5.4-train.py {input} --model vit_small_patch32_224 --num-classes=10 --output {output[0]} --checkpoint-hist 2 --epochs 80 --experiment after80 --mean 0.485 0.456 0.406 --std 0.229 0.224 0.225 -b 96 > {log} 2>&1"

rule imagenette2_train_all:
    input:
        expand("outputs/{arch}/seed42/fold-{fid:02.0f}/after80/last.pth.tar",
               arch="resnext50,resnet50,vit_small".split(','),
               fid=range(KFOLDS)),
        expand("outputs/{arch}/seed{seedval:02.0f}/fold-{fid:02.0f}/after80/last.pth.tar",
               arch="resnext50,resnet50,vit_small".split(','),
               seedval=range(1328,1328+KFOLDS),
               fid=range(KFOLDS))

rule imagenette2_train:
    input:
        expand("outputs/{arch}/seed42/fold-{fid:02.0f}/after80/last.pth.tar",
               arch="resnext50,resnet50,vit_small".split(','),
               fid=range(KFOLDS))

rule imagenette2_train_varseed:
    input:
        expand("outputs/{arch}/seed{seedval:02.0f}/fold-{fid:02.0f}/after80/last.pth.tar",
               arch="resnext50,resnet50,vit_small".split(','),
               seedval=range(1328,1328+KFOLDS),
               fid=range(KFOLDS))
