cluster: "sbatch --time={resources.time_min} --mem={resources.mem_mb}
          -c {resources.cpus} -p gpus -A atmlaml 
          -o outputs/slurm/logs/{rule}_%A.out -e outputs/slurm/logs/{rule}_%A.err"
jobs: 64
default-resources: [cpus=1, mem_mb=30000, time_min=200, ngpu=1]
resources: [cpus=100, mem_mb=800000]
