cluster: "sbatch --time={resources.time_min} --mem={resources.mem_mb}
          -c {resources.cpus} -p {resources.partition} --gres=gpu:{resources.ngpu}
          -o outputs/slurm/logs/{rule}_%j.out -e outputs/slurm/logs/{rule}_%j.err -J {rule}"
jobs: 64
default-resources: [cpus=4, mem_mb=30000, time_min=75, ngpu=1, partition="gpu"]
resources: [cpus=100, mem_mb=800000]
set-resources:
  - imagenette2_inference:time_min=90
  - imagenette2_inference_last:time_min=5
  - imagenette2_resnext50_inference_last:time_min=5
  - imagenette2_resnet50_inference_last:time_min=5
  - imagenette2_vit_small_inference_last:time_min=5
  - imagenette2_inference_best:time_min=5
  - imagenette2_resnext50_inference_best:time_min=5
  - imagenette2_resnet50_inference_best:time_min=5
  - imagenette2_vit_small_inference_best:time_min=5
  - create_tables:time_min=30
  - download_imagenette:time_min=10
  - imagenette_combine:time_min=30
  - imagenette_tables:time_min=20
  - imagenette_trainval_merged:time_min=5
  - imagenette_unpack:time_min=30

